#!/bin/bash

set -e
./check-root

# Set Hostname
echo 'Enter a Hostname:'
read hstnme
echo $hstnme > /etc/hostname


# Lock the root account
passwd -l root


# Setup repositories
# RPM Fusion free
dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
# RPM Fusion non-free
dnf install -y https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm


# Remove unwanted software
# System Software

# GUI software
dnf remove -y cheese eog evolution gnome-{boxes,characters,clocks,documents,font-viewer,maps} rhythmbox shotwell


# Software Installs
# CLI tools
dnf install -y nano

# Generic OS GUI software and Gnome packages
dnf install -y deja-dup deja-dup-nautilus gedit-code-assistance gedit-plugins geary gimp gnome-{music,terminal-nautilus,tweak-tool} gthumb simple-scan

# Keepassx
dnf install -y keepassxc

# Dropbox
dnf install -y dropbox nautilus-dropbox

# Language tools
dnf install -y hunspell-en-GB

# Add required packages for mp3 playback (ffmpeg / gstreamer)
dnf install -y gstreamer1-plugins-{base,good,ugly,bad-{free,freeworld,free-extras}} ffmpeg

# Powerline
dnf install -y powerline powerline-fonts
cat <<EOF >> /etc/bashrc

# Powerline
if [ -f `which powerline-daemon` ]; then
  powerline-daemon -q
  POWERLINE_BASH_CONTINUATION=1
  POWERLINE_BASH_SELECT=1
  . /usr/share/powerline/bash/powerline.sh
fi
EOF

# Google Chrome
wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
dnf install -y google-chrome-stable_current_x86_64.rpm
rm google-chrome-stable_current_x86_64.rpm

# Zotero
cwd=$(pwd)
cd install_scripts/zotero
./zotero
cd $cwd

# Shell extensions
# From repos
dnf install -y gnome-shell-extension-{alternate-tab,common,drive-menu,openweather,places-menu,pomodoro,topicons-plus}
# dash-to-dock
./install_scripts/dash-to-dock

# Theming
# Backroungs
dnf install -y f26-backgrounds-animated
# gtk theme
dnf copr enable -y heikoada/gtk-themes
dnf install -y adapta-gtk-theme
# Papirus icon theme
dnf copr enable -y dirkdavidis/papirus-icon-theme
dnf install -y papirus-icon-theme


./configure-system-defaults


# For existing users:
for dir in /home/*; do
    if [ ! $dir = "/home/lost+found" ]; then
        # Get user name
        user="$(basename $dir)"
        # File Templates
        rsync -a Templates $dir
        chown $user:$user -R $dir/Templates
        # Reset all dconf keys to default
        sudo -u $user dconf reset -f /
    fi
done
